  services:
    db:
      image: postgres:15
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 5s
        retries: 5

    app:
      build: .
      depends_on:
        db:
          condition: service_healthy
      environment:
        DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/postgres
      ports:
        - "8048:8048"
      command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8048"]
